import {doc,getDoc,setDoc,updateDoc,deleteDoc,onSnapshot,collection,query,where,runTransaction,serverTimestamp,Timestamp,getDocs,orderBy,limit} from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-firestore.js';
import {getAuth,EmailAuthProvider,linkWithCredential,signInWithEmailAndPassword,sendPasswordResetEmail,sendEmailVerification,signOut} from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-auth.js';
import {normalizeNumber,formatNumber} from './number-call-policy.js';
import {isLeaseLive,canJoinGroup} from './phone-policy.js';
export function createPhoneApp({db,user,state,name,navigate,stop,notice,push,usage:report=()=>{}}){
 const $=id=>document.getElementById(id),uid=user.uid,auth=getAuth(db.app),params=new URLSearchParams(location.search);
 const ref=(c,id)=>doc(db,c,id),profile=ref('numberProfiles',uid),busyRef=id=>ref('phoneBusy',id),requestRef=id=>ref('numberInvitations',id);
 let own='',contacts=[],groups=[],incoming=null,outgoing=false,ringOff=null,ringTimer=null,incomingTimer=null,busy=false,currentRoom=null,selectedGroup=null,usage={reads:0,writes:0};
 const queue=new Set();let roomOff=null,groupPeopleOff=null,groupDetailOff=null,groupInvites=[];
 try{usage=JSON.parse(sessionStorage.getItem('number-call-setup:'+state().callId)||'null')||usage;sessionStorage.removeItem('number-call-setup:'+state().callId);}catch(_){}
 function count(r,w=0){if(state().joined)report(r,w);else{usage.reads+=r;usage.writes+=w;}}
 async function read(r){const s=await getDoc(r);count(1);return s;}
 async function write(r,d){await setDoc(r,d);count(0,1);}
 async function patch(r,d){await updateDoc(r,d);count(0,1);}
 async function remove(r){await deleteDoc(r);count(0,1);}
 function watch(r,fn){return onSnapshot(r,s=>{if(!s.metadata.fromCache)count(s.docChanges?Math.max(1,s.docChanges().length):1);fn(s);},e=>msg('接続を確認して、再読み込みしてください。'));}
 async function tx(fn){let writes=0;const value=await runTransaction(db,async t=>{writes=0;return fn({get:async r=>{const s=await t.get(r);count(1);return s;},set:(...a)=>{writes++;t.set(...a);},update:(...a)=>{writes++;t.update(...a);},delete:(...a)=>{writes++;t.delete(...a);}});});count(0,writes);return value;}
 function msg(t){$('phoneMessage').textContent=t;notice(t);}
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function go(id){sessionStorage.setItem('number-call-setup:'+id,JSON.stringify(usage));navigate(id);}
 function tab(id){for(const b of document.querySelectorAll('[data-phone-tab]')){const active=b.dataset.phoneTab===id;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;if(active){const host=b.parentElement,left=b.offsetLeft-host.offsetLeft;if(left<host.scrollLeft)host.scrollLeft=left;else if(left+b.offsetWidth>host.scrollLeft+host.clientWidth)host.scrollLeft=left+b.offsetWidth-host.clientWidth;}$(b.getAttribute('aria-controls')).hidden=!active;}}
 function home(id='dial'){if(state().joined){msg('通話を終了してからホームへ戻ってください。');return;}const u=new URL(location.origin+location.pathname);u.searchParams.set('tab',id);location.assign(u);}
 async function copy(t){try{await navigator.clipboard.writeText(t);msg('コピーしました。');}catch(_){msg(t);}}
 function numberLink(){const u=new URL(location.origin+location.pathname);u.searchParams.set('contact',own);return u.toString();}
 async function createNumber(){if(busy)return;const display=$('phoneName').value.trim();if(!display){$('phoneNameDialog').showModal();$('phoneNameMessage').textContent='番号を作る前に、名前を保存してください。';$('phoneName').focus();return;}busy=true;
  try{for(let i=0;i<10;i++){const n=crypto.getRandomValues(new Uint32Array(1))[0];if(n>=4200000000){i--;continue;}const number=String(n%1e8).padStart(8,'0');const value=await tx(async t=>{const p=await t.get(profile);if(p.exists())return p.data().number;const s=await t.get(ref('voiceNumbers',number));if(s.exists())return null;t.set(ref('voiceNumbers',number),{number,ownerUid:uid});t.set(profile,{number,name:display.slice(0,20)});return number;});if(value){own=value;renderOwn();msg('自分の番号を作成しました。');return;}}throw Error();}catch(_){msg('番号を作れませんでした。通信を確認してください。');}finally{busy=false;}}
 function renderOwn(){$('phoneOwnNumber').textContent=own?formatNumber(own):'番号を設定してください';$('phoneCreateNumber').hidden=!!own;$('phoneShare').hidden=!own;$('phoneCopy').hidden=!own;}
 async function saveName(){const value=Array.from($('phoneName').value.normalize('NFKC').replace(/\s+/g,' ').trim()).slice(0,8).join('');if(!value){$('phoneNameMessage').textContent='名前を入力してください。';return;}if(own)await patch(profile,{name:value});$('phoneName').value=value;$('nameInput').value=value;$('nameInput').dispatchEvent(new Event('change',{bubbles:true}));$('phoneNameOpen').title=value+'：名前を編集';$('phoneNameDialog').close();msg('名前を保存しました。');}

 function myName(){return $('nameInput').value.trim().slice(0,8)||name();}
 async function addContact(number=$('phoneContactNumber').value,alias=$('phoneContactName').value){const n=normalizeNumber(number);if(!n||!alias.trim()){msg('8桁の番号と登録名を入力してください。');return;}const s=await read(ref('voiceNumbers',n));if(!s.exists()||s.data().ownerUid===uid){msg('相手の番号を確認してください。');return;}await write(doc(db,'numberProfiles',uid,'contacts',n),{number:n,name:alias.trim().slice(0,40),uid:s.data().ownerUid});$('phoneContactNumber').value='';$('phoneContactName').value='';msg('電話帳に登録しました。相手側には自動登録されません。');}
 function renderContacts(){$('phoneContacts').innerHTML=contacts.length?contacts.map(c=>`<article class="phone-row"><div><strong>${esc(c.name)}</strong><small>${esc(formatNumber(c.number))}</small></div><button data-dial="${c.number}">電話する</button><button data-edit="${c.number}">編集</button><button data-remove-contact="${c.number}" aria-label="${esc(c.name)}を削除">削除</button></article>`).join(''):'<p>相手の番号を登録すると、ここから電話できます。</p>';$('groupInviteContact').innerHTML='<option value="">電話帳から選ぶ</option>'+contacts.map(c=>`<option value="${esc(c.uid)}">${esc(c.name)}</option>`).join('');}
 async function history(id,data){try{await write(doc(db,'numberProfiles',uid,'history',id),{...data,at:Date.now()});}catch(_){}}
 function renderHistory(items){$('phoneHistory').innerHTML=items.sort((a,b)=>b.at-a.at).slice(0,20).map(h=>`<article class="phone-row"><div><strong>${esc(h.name||h.number||'相手')}</strong><small>${esc(({outgoing:'発信',incoming:'着信'})[h.direction])}・${esc(({ringing:'呼び出し中',accepted:'応答済み',declined:'拒否',cancelled:'取消',busy:'通話中',missed:'不在着信'})[h.status]||h.status)}・${new Date(h.at).toLocaleString('ja-JP')}</small></div>${h.number?`<button data-register="${esc(h.number)}" data-name="${esc(h.name)}">電話帳に登録</button><button data-dial="${esc(h.number)}">電話する</button>`:''}</article>`).join('')||'<p>発着信履歴はまだありません。</p>';}
 async function available(t,id){const s=await t.get(busyRef(id));if(!s.exists()||!isLeaseLive(s.data(),Date.now()))return true;const b=s.data();if(b.callId.startsWith('n_')){const r=await t.get(ref('numberVoiceCalls',b.callId));return !r.exists()||!r.data().active;}return false;}
 async function dial(value){if(busy||outgoing)return;if(state().joined){msg('通話を終了してから発信してください。');return;}const number=normalizeNumber(value);if(!number){msg('8桁の番号を入力してください。');return;}if(!own){msg('先に自分の番号を作成してください。');return;}busy=true;
  try{const target=await read(ref('voiceNumbers',number));if(!target.exists()||target.data().ownerUid===uid)throw Error('相手の番号を確認してください。');const to=target.data().ownerUid;const id=uid+'_'+Date.now();
   // Even busy calls are recorded as requests so the callee gets a missed-call entry.
   await write(requestRef(uid),{from:uid,to,number,fromNumber:own,name:myName(),status:'ringing',createdAt:serverTimestamp(),expiresAt:Timestamp.fromMillis(Date.now()+85000)});
   outgoing=true;$('phoneCancel').hidden=false;msg('呼び出し中…');await history(id,{number,name:contacts.find(c=>c.number===number)?.name||formatNumber(number),status:'ringing',direction:'outgoing'});
   ringOff=watch(requestRef(uid),s=>{const r=s.data();if(!outgoing||!r)return;if(r.status==='accepted'){finishRing();history(id,{number,name:formatNumber(number),status:r.status,direction:'outgoing'}).then(()=>go(r.roomId));}else if(r.status!=='ringing'){finishRing();history(id,{number,name:formatNumber(number),status:r.status,direction:'outgoing'});msg(r.status==='busy'?'相手は通話中です。':r.status==='declined'?'相手が応答を見送りました。':'呼び出しを終了しました。');}});
   ringTimer=setTimeout(()=>cancel('応答がありませんでした。'),85000);
   const targetBusy=await read(busyRef(to));if(!isLeaseLive(targetBusy.data(),Date.now()))push?.(to,uid+Date.now()).catch(()=>{});
  }catch(e){msg(e.code==='permission-denied'?'発信できません。連続発信の場合は30秒以上待ってください。':e.message||'発信できませんでした。');}finally{busy=false;}}
 function finishRing(){outgoing=false;ringOff?.();ringOff=null;clearTimeout(ringTimer);$('phoneCancel').hidden=true;}
 async function cancel(text='呼び出しを取り消しました。'){if(!outgoing)return;finishRing();try{await patch(requestRef(uid),{status:'cancelled'});}catch(_){}msg(text);}
 async function receive(items){const now=Date.now();for(const r of items){if(!r.createdAt)continue;const id=r.from+'_'+r.createdAt.toMillis();if(queue.has(id))continue;if(r.status==='ringing'&&r.expiresAt.toMillis()>now){if(state().joined||!(await available({get:read},uid))){queue.add(id);await patch(requestRef(r.from),{status:'busy'}).catch(()=>{});await history(id,{number:r.fromNumber||'',name:r.name,status:'busy',direction:'incoming'});}}}
  incoming=items.filter(r=>r.createdAt&&r.status==='ringing'&&r.expiresAt.toMillis()>Date.now()&&!queue.has(r.from+'_'+r.createdAt.toMillis())).sort((a,b)=>a.createdAt.toMillis()-b.createdAt.toMillis())[0]||null;clearTimeout(incomingTimer);
  if(!incoming){$('numberIncoming').close();return;}const id=incoming.from+'_'+incoming.createdAt.toMillis();history(id,{number:incoming.fromNumber||'',name:incoming.name,status:'ringing',direction:'incoming'});$('numberCaller').textContent=(contacts.find(c=>c.number===incoming.fromNumber)?.name||incoming.name)+'さんから着信';$('numberIncomingText').textContent='応答すると1対1の電話が始まります。';$('numberAccept').textContent='応答する';if(!$('numberIncoming').open)$('numberIncoming').showModal();incomingTimer=setTimeout(()=>{history(id,{number:incoming.fromNumber||'',name:incoming.name,status:'missed',direction:'incoming'});receive(items);},Math.max(1,incoming.expiresAt.toMillis()-Date.now()+50));}
 async function respond(accept){if(busy||!incoming)return;busy=true;const r=incoming,id=r.from+'_'+r.createdAt.toMillis();$('numberAccept').disabled=true;
  try{if(!accept){await patch(requestRef(r.from),{status:'declined'});await history(id,{number:r.fromNumber||'',name:r.name,status:'declined',direction:'incoming'});return;}if(state().joined)throw Error('現在の通話を終了してから応答してください。');const callId='n_'+crypto.randomUUID().replaceAll('-','');
   await tx(async t=>{const pending=await t.get(requestRef(r.from));if(pending.data()?.status!=='ringing'||pending.data().expiresAt.toMillis()<=Date.now())throw Error('この着信は終了しました。');const selfFree=await available(t,uid),otherFree=await available(t,r.from);if(!selfFree||!otherFree)throw Error('どちらかが通話中です。');t.set(ref('numberVoiceCalls',callId),{ownerUid:uid,number:own,members:[uid,r.from],active:true,expiresAt:Timestamp.fromMillis(Date.now()+65*60000)});t.update(requestRef(r.from),{status:'accepted',roomId:callId});for(const person of [uid,r.from])t.set(busyRef(person),{callId,until:Timestamp.fromMillis(Date.now()+240000)});});
   queue.add(id);$('numberIncoming').close();await history(id,{number:r.fromNumber||'',name:r.name,status:'accepted',direction:'incoming'});go(callId);
  }catch(e){$('numberIncomingText').textContent=e.message||'応答できませんでした。';}finally{busy=false;$('numberAccept').disabled=false;}}
 async function block(){const r=incoming;if(!r)return;await write(doc(db,'voiceNumbers',own,'blocked',r.from),{name:r.name,number:r.fromNumber||''});await respond(false);}
 function groupLink(g){const u=new URL(location.origin+location.pathname);u.searchParams.set('groupInvite',g.id);return u.toString();}
 async function createGroup(){const title=$('phoneGroupName').value.trim().slice(0,40);if(!title){msg('グループ名を入力してください。');return;}const id='g_'+crypto.randomUUID().replaceAll('-','');await write(ref('phoneGroups',id),{name:title,ownerUid:uid,members:[uid],active:true});$('phoneGroupName').value='';await openGroup(id);msg('グループを作成しました。電話帳かリンクから招待してください。');}
 function renderInvites(){$('phoneGroupInvites').innerHTML=groupInvites.filter(d=>!groups.some(g=>g.id===d.groupId)).map(d=>`<article class="phone-row"><span>${esc(d.name)}への招待</span><button data-open-group="${esc(d.groupId)}">招待を確認</button></article>`).join('');}
 function renderGroups(){renderInvites();$('phoneGroups').innerHTML=groups.map(g=>`<article class="phone-row"><div><strong>${esc(g.name)}</strong><small>${g.members.length}/4人</small></div><button data-open-group="${esc(g.id)}">開く</button></article>`).join('')||'<p>同じテーマで話すグループを作れます。</p>';}
 async function openGroup(id){const s=await read(ref('phoneGroups',id));if(!s.exists()||!s.data().active){msg('このグループは終了しています。');return;}selectedGroup={...s.data(),id};const g=selectedGroup;$('groupTitle').textContent=g.name;$('groupMembers').textContent=g.members.length+'/4人のグループ';$('groupAcceptInvite').hidden=g.members.includes(uid);$('groupJoin').hidden=!g.members.includes(uid);$('groupShare').hidden=!g.members.includes(uid);$('groupInviteArea').hidden=!g.members.includes(uid);$('groupDelete').hidden=g.ownerUid!==uid;$('groupQuit').hidden=g.ownerUid===uid||!g.members.includes(uid);$('groupDialog').showModal();groupDetailOff?.();groupDetailOff=watch(ref('phoneGroups',id),snap=>{if(!snap.data()?.active){$('groupDialog').close();return;}selectedGroup={...snap.data(),id};$('groupMembers').textContent=selectedGroup.members.length+'/4人のグループ';});groupPeopleOff?.();$('groupPeople').textContent='参加するとマイクを使います。';if(g.members.includes(uid))groupPeopleOff=watch(query(collection(db,'groupVoiceCalls',id,'participants'),where('left','==',false)),s=>{const active=s.docs.map(d=>d.data()).filter(d=>Date.now()-(d.lastSeenAt?.toMillis()||0)<240000);$('groupPeople').textContent=active.length?'通話中：'+active.map(d=>d.userName).join('、'):'いま通話中の人はいません。';});}
 async function acceptGroup(){const id=selectedGroup?.id;if(!id)return;await tx(async t=>{const s=await t.get(ref('phoneGroups',id)),g=s.data();if(!canJoinGroup(g,uid))throw Error('グループが満員、または終了しています。');if(!g.members.includes(uid))t.update(ref('phoneGroups',id),{members:[...g.members,uid]});});await openGroup(id);msg('グループに登録しました。通話するには「通話に参加」を押してください。');}
 async function joinGroup(){if(state().joined){msg('今の通話を終了してから参加してください。');return;}const id=selectedGroup?.id;if(!id)return;await tx(async t=>{const s=await t.get(ref('phoneGroups',id));if(!s.data()?.active||!s.data().members.includes(uid))throw Error('グループへの登録が必要です。');if(!(await available(t,uid)))throw Error('別の端末で通話中です。');t.set(busyRef(uid),{callId:id,until:Timestamp.fromMillis(Date.now()+240000)});});go(id);}
 async function inviteContact(){const to=$('groupInviteContact').value,g=selectedGroup;if(!to||!g)return;if(g.members.length>=4){msg('グループは4人までです。');return;}await write(ref('phoneGroupInvites',g.id+'_'+to),{groupId:g.id,to,from:uid,name:g.name,status:'invited'});msg('グループへの招待を送りました。');}
 async function quitGroup(deleting){const g=selectedGroup;if(!g)return;if(!confirm(deleting?'このグループを削除しますか？全員が利用できなくなります。':'グループから退出しますか？再参加には招待リンクが必要です。'))return;if(deleting)await patch(ref('phoneGroups',g.id),{active:false});else await tx(async t=>{const s=await t.get(ref('phoneGroups',g.id));t.update(ref('phoneGroups',g.id),{members:s.data().members.filter(x=>x!==uid)});});$('groupDialog').close();}
 async function account(mode){if(state().joined||outgoing){msg('通話・呼び出しを終了してから操作してください。');return;}const email=$('phoneEmail').value.trim(),password=$('phonePassword').value;try{if(mode==='save'){await linkWithCredential(user,EmailAuthProvider.credential(email,password));$('accountStatus').textContent='番号を引き継げるようにしました。';try{await sendEmailVerification(user);$('accountStatus').textContent+='確認メールをご確認ください。';}catch(_){$('accountStatus').textContent+='確認メールの送信は再度お試しください。';}$('phonePassword').value='';}else if(mode==='login'){if(own&&user.isAnonymous&&!confirm('現在の番号は自動統合されません。登録済みのアカウントへ切り替えますか？'))return;await signInWithEmailAndPassword(auth,email,password);location.assign(location.origin+location.pathname);}else if(mode==='reset'){await sendPasswordResetEmail(auth,email);$('accountStatus').textContent='登録済みのメールアドレスの場合、再設定メールが届きます。';}else{if(user.isAnonymous){$('accountStatus').textContent='先に「この番号を保存」を設定してください。';return;}await signOut(auth);location.assign(location.origin+location.pathname);}}catch(e){$('accountStatus').textContent=e.code==='auth/email-already-in-use'?'このメールは登録済みです。「ログイン」をお試しください。':e.code==='auth/weak-password'?'パスワードは6文字以上にしてください。':'操作できませんでした。メール・パスワード・通信状態を確認してください。';}}
 async function allowed(){const id=state().callId;try{if(id.startsWith('n_')){const s=await read(ref('numberVoiceCalls',id));currentRoom=s.data();return !!currentRoom?.active&&currentRoom.members.length===2&&currentRoom.members.includes(uid)&&currentRoom.expiresAt.toMillis()>Date.now();}if(id.startsWith('g_')){const s=await read(ref('phoneGroups',id));return !!s.data()?.active&&s.data().members.includes(uid);}return false;}catch(_){return false;}}
 async function acquire(){if(!(await allowed()))return false;const id=state().callId;await tx(async t=>{const b=await t.get(busyRef(uid));if(isLeaseLive(b.data(),Date.now())&&b.data().callId!==id)throw Error('別の通話に参加中です。');t.set(busyRef(uid),{callId:id,until:Timestamp.fromMillis(Date.now()+240000)});});return true;}
 async function pulse(){if(!state().joined)return;try{await patch(busyRef(uid),{until:Timestamp.fromMillis(Date.now()+240000)});}catch(_){stop();msg('通話の状態を確認できないため終了しました。');}}
 async function leave(){const id=state().callId;try{await tx(async t=>{const b=await t.get(busyRef(uid));let room;if(id.startsWith('n_'))room=await t.get(ref('numberVoiceCalls',id));if(room?.data()?.active)t.update(ref('numberVoiceCalls',id),{active:false});if(b.data()?.callId===id)t.delete(busyRef(uid));});}catch(_){}document.body.classList.add('phone-home');}
 async function start(){
  document.body.classList.toggle('phone-home',!/^n_|^g_/.test(state().callId));
  document.querySelector('.participant-limit').textContent=state().callId.startsWith('n_')?'1対1':'最大4人';$('phoneToGroup').hidden=!state().callId.startsWith('n_');
  $('phoneName').value=name()==='匿名さん'?'':name();$('accountStatus').textContent=user.isAnonymous?'番号・電話帳・グループを別の端末へ引き継ぐには、メールとパスワードを登録してください。':user.email+'でログイン中';
  for(const b of document.querySelectorAll('[data-phone-tab]'))b.onclick=()=>tab(b.dataset.phoneTab);
  $('shareBtn').textContent=state().callId.startsWith('g_')?'招待リンク':'番号を共有';$('shareBtn').addEventListener('click',e=>{e.stopImmediatePropagation();copy(state().callId.startsWith('g_')?groupLink({id:state().callId}):numberLink());},true);
  const bind=(id,fn)=>$(id).addEventListener('click',async()=>{const b=$(id);b.disabled=true;try{await fn();}catch(e){msg(e.message||'操作できませんでした。');}finally{b.disabled=false;}});
  bind('phoneCreateNumber',createNumber);bind('phoneCopy',()=>copy(own));bind('phoneShare',()=>copy(numberLink()));bind('phoneCancel',()=>cancel());bind('phoneAddContact',()=>addContact());bind('phoneCreateGroup',createGroup);
  $('phoneNameOpen').onclick=()=>{$('phoneNameMessage').textContent='';$('phoneNameDialog').showModal();$('phoneName').focus();};
  $('phoneNameClose').onclick=()=>{$('phoneName').value=$('nameInput').value;$('phoneNameDialog').close();};
  $('phoneNameDialog').addEventListener('cancel',()=>{$('phoneName').value=$('nameInput').value;});
  $('phoneNameForm').addEventListener('submit',async e=>{e.preventDefault();$('phoneSaveName').disabled=true;try{await saveName();}catch(_){$('phoneNameMessage').textContent='保存できませんでした。通信を確認してください。';}finally{$('phoneSaveName').disabled=false;}});
  const tabs=document.querySelector('.phone-tabs');tabs.addEventListener('wheel',e=>{if(e.ctrlKey||tabs.scrollWidth<=tabs.clientWidth)return;const before=tabs.scrollLeft;tabs.scrollLeft+=Math.abs(e.deltaX)>Math.abs(e.deltaY)?e.deltaX:e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?tabs.clientWidth:1);if(before!==tabs.scrollLeft)e.preventDefault();},{passive:false});
  tabs.addEventListener('keydown',e=>{const buttons=[...tabs.querySelectorAll('[data-phone-tab]')],i=buttons.indexOf(document.activeElement);if(i<0||!['ArrowRight','ArrowLeft','Home','End'].includes(e.key))return;e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?buttons.length-1:(i+(e.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;tab(buttons[next].dataset.phoneTab);buttons[next].focus();});
  const input=$('phoneDialNumber');let cursor=null,endCursor=null;input.addEventListener('select',()=>{cursor=input.selectionStart;endCursor=input.selectionEnd;});input.addEventListener('blur',()=>{cursor=input.selectionStart;endCursor=input.selectionEnd;});
  function editDial(key){const a=cursor??input.value.length,b=endCursor??a;const left=key===null?Math.max(0,a-(a===b?1:0)):a;const value=input.value.slice(0,left)+(key||'')+input.value.slice(b);if(value.length>input.maxLength)return;input.value=value;cursor=endCursor=left+(key?key.length:0);input.setSelectionRange(cursor,cursor);input.dispatchEvent(new Event('input',{bubbles:true}));}
  for(const b of document.querySelectorAll('[data-phone-key]'))b.onclick=()=>editDial(b.dataset.phoneKey);
  $('phoneBackspace').onclick=()=>editDial(null);
  $('phoneDialForm').addEventListener('submit',e=>{e.preventDefault();dial($('phoneDialNumber').value);});
  bind('numberAccept',()=>respond(true));bind('numberDecline',()=>respond(false));bind('numberBlock',block);$('numberIncoming').addEventListener('cancel',e=>{e.preventDefault();respond(false);});
  bind('groupClose',()=>{$('groupDialog').close();groupPeopleOff?.();groupDetailOff?.();});bind('groupAcceptInvite',acceptGroup);bind('groupJoin',joinGroup);bind('groupShare',()=>copy(groupLink(selectedGroup)));bind('groupInviteSend',inviteContact);bind('groupDelete',()=>quitGroup(true));bind('groupQuit',()=>quitGroup(false));
  for(const mode of ['save','login','reset','logout'])bind('account-'+mode,()=>account(mode));
  bind('phoneHomeBtn',()=>home());bind('phoneToGroup',async()=>{if(!confirm('今の電話を終了して、グループ画面へ移動します。相手にはグループ作成後に招待を送ってください。'))return;await leave();stop();home('groups');});
  $('phoneHome').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.legacyName){$('phoneContactName').value=d.legacyName;$('phoneContactNumber').value='';$('phoneContactNumber').focus();}if(d.dial)dial(d.dial);if(d.register){tab('contacts');$('phoneContactNumber').value=d.register;$('phoneContactName').value=d.name||'';}if(d.edit){const c=contacts.find(c=>c.number===d.edit);$('phoneContactNumber').value=c.number;$('phoneContactName').value=c.name;}if(d.removeContact&&confirm('電話帳から削除しますか？'))remove(doc(db,'numberProfiles',uid,'contacts',d.removeContact));if(d.openGroup)openGroup(d.openGroup);if(d.unblock)remove(doc(db,'voiceNumbers',own,'blocked',d.unblock));});
  const p=await read(profile);own=p.data()?.number||'';if(p.data()?.name){$('phoneName').value=p.data().name;$('nameInput').value=p.data().name;}renderOwn();
  watch(query(collection(db,'voiceConnections'),where('members','array-contains',uid)),s=>{const previous=s.docs.map(d=>d.data()).filter(d=>d.active!==false);$('legacyPhonebook').hidden=!previous.length;$('legacyPhoneContacts').innerHTML=previous.map(d=>{const n=d.uidA===uid?d.nameB:d.nameA;return '<article class="phone-row"><span>'+esc(n||'相手')+'</span><button data-legacy-name="'+esc(n||'相手')+'">番号を登録</button></article>';}).join('');});
  watch(collection(db,'numberProfiles',uid,'contacts'),s=>{contacts=s.docs.map(d=>d.data());renderContacts();});
  watch(query(collection(db,'numberProfiles',uid,'history'),orderBy('at','desc'),limit(20)),s=>renderHistory(s.docs.map(d=>d.data())));
  watch(query(collection(db,'phoneGroups'),where('members','array-contains',uid)),s=>{groups=s.docs.map(d=>({...d.data(),id:d.id})).filter(g=>g.active);renderGroups();});
  watch(query(collection(db,'phoneGroupInvites'),where('to','==',uid)),s=>{groupInvites=s.docs.map(d=>d.data());renderInvites();});
  watch(query(collection(db,'numberInvitations'),where('to','==',uid),where('status','==','ringing')),s=>receive(s.docs.map(d=>d.data())).catch(()=>{}));
  if(own)watch(collection(db,'voiceNumbers',own,'blocked'),s=>{$('phoneBlocks').innerHTML=s.docs.map(d=>`<div class="phone-row"><span>${esc(d.data().name||d.data().number||'相手')}</span><button data-unblock="${esc(d.id)}">解除</button></div>`).join('')||'ブロックした相手はいません。';});
  if(/^n_|^g_/.test(state().callId))roomOff=watch(ref(state().callId.startsWith('n_')?'numberVoiceCalls':'phoneGroups',state().callId),s=>{currentRoom=s.data();if(state().joined&&(!currentRoom?.active||!currentRoom.members.includes(uid))){stop();leave();msg('通話が終了しました。');}});
  window.addEventListener('pagehide',()=>{if(outgoing)cancel();});tab(['history','contacts','dial','groups','settings'].includes(params.get('tab'))?params.get('tab'):'dial');
  if(normalizeNumber(params.get('contact')||'')){tab('contacts');$('phoneContactNumber').value=normalizeNumber(params.get('contact'));msg('登録する名前を入力して「登録」を押してください。');}
  if(params.get('groupInvite')?.match(/^g_[a-f0-9]{32}$/)){tab('groups');await openGroup(params.get('groupInvite'));}
 }
 return {start,allowed,acquire,pulse,leave,takeSetupUsage(){const u=usage;usage={reads:0,writes:0};return u;}};
}
