import {bindDialInput} from './dial-input.js';
import {copyNumberFeedback} from './copy-feedback.js?v=2026-09-04-phone-details';
import {doc,getDoc,setDoc,updateDoc,deleteDoc,onSnapshot,collection,query,where,runTransaction,serverTimestamp,Timestamp,getDocs,orderBy,limit} from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-firestore.js';
import {getAuth,EmailAuthProvider,linkWithCredential,signInWithEmailAndPassword,sendPasswordResetEmail,sendEmailVerification,signOut} from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-auth.js';
import {normalizeNumber,formatNumber} from './number-call-policy.js';
import {isLeaseLive,canJoinGroup} from './phone-policy.js';
import {historyLabels,formatDuration,groupHistory,filterPhoneItems,preferredHistoryName,formatHistoryDate,frequentHistoryTargets,groupContacts} from './phone-presentation.js?v=2026-09-04-history-layout';
export function createPhoneApp({db,user,state,name,navigate,stop,notice,push,notifications={},usage:report=()=>{}}){
 const $=id=>document.getElementById(id),uid=user.uid,auth=getAuth(db.app),params=new URLSearchParams(location.search);
 const ref=(c,id)=>doc(db,c,id),profile=ref('numberProfiles',uid),busyRef=id=>ref('phoneBusy',id),requestRef=id=>ref('numberInvitations',id);
 let own='',contacts=[],historyItems=[],groups=[],incoming=null,outgoing=false,outgoingTargetUid='',outgoingPushId='',outgoingNumber='',outgoingName='',outgoingMode='support',ringOff=null,ringTimer=null,incomingTimer=null,busy=false,currentRoom=null,selectedGroup=null,usage={reads:0,writes:0};
 let ringAudio=null,ringAudioTimer=null,messageTimer=null,messageClearTimer=null;
 let confirmationResolve=null;
 const queue=new Set();let roomOff=null,groupPeopleOff=null,groupDetailOff=null,groupInvites=[],activeHistory=null;
 try{usage=JSON.parse(sessionStorage.getItem('number-call-setup:'+state().callId)||'null')||usage;sessionStorage.removeItem('number-call-setup:'+state().callId);}catch(_){}
 function count(r,w=0){if(state().joined)report(r,w);else{usage.reads+=r;usage.writes+=w;}}
 async function read(r){const s=await getDoc(r);count(1);return s;}
 async function write(r,d){await setDoc(r,d);count(0,1);}
 async function patch(r,d){await updateDoc(r,d);count(0,1);}
 async function remove(r){await deleteDoc(r);count(0,1);}
 function watch(r,fn){return onSnapshot(r,s=>{if(!s.metadata.fromCache)count(s.docChanges?Math.max(1,s.docChanges().length):1);fn(s);},e=>msg('接続を確認して、再読み込みしてください。'));}
 async function tx(fn){let writes=0;const value=await runTransaction(db,async t=>{writes=0;return fn({get:async r=>{const s=await t.get(r);count(1);return s;},set:(...a)=>{writes++;t.set(...a);},update:(...a)=>{writes++;t.update(...a);},delete:(...a)=>{writes++;t.delete(...a);}});});count(0,writes);return value;}
 function msg(t){const box=$('phoneMessage');clearTimeout(messageTimer);clearTimeout(messageClearTimer);box.textContent=t;box.classList.add('is-visible');messageTimer=setTimeout(()=>{box.classList.remove('is-visible');messageClearTimer=setTimeout(()=>{if(!box.classList.contains('is-visible'))box.textContent='';},260);},4000);notice(t);}
 function syncAccountActions(){const actions=$('accountActions'),ready=$('phoneEmail').value.length>0&&$('phonePassword').value.length>0;actions.hidden=!ready;}
 function closeConfirmation(answer=false){const dialog=$('phoneConfirmDialog');if(dialog.open)dialog.close();const resolve=confirmationResolve;confirmationResolve=null;if(resolve)resolve(answer);}
 function askConfirmation(message,{title='確認',confirmLabel='続ける',danger=false}={}){closeConfirmation(false);$('phoneConfirmTitle').textContent=title;$('phoneConfirmMessage').textContent=message;$('phoneConfirmOk').textContent=confirmLabel;$('phoneConfirmOk').classList.toggle('is-danger',danger);const dialog=$('phoneConfirmDialog');dialog.showModal();return new Promise(resolve=>{confirmationResolve=resolve;});}
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const defaultModeKey='kouryu-default-support-mode-v1';
 const mode=value=>value==='plain'?'plain':'support', modeLabel=value=>mode(value)==='plain'?'通話だけ':'理解サポートあり';
 const defaultMode=()=>mode(localStorage.getItem(defaultModeKey));
 function selectedMode(name){return mode(document.querySelector('input[name="'+name+'"]:checked')?.value)}
 function go(id,supportMode='support'){const selected=mode(supportMode);sessionStorage.setItem('number-call-setup:'+id,JSON.stringify(usage));if(activeHistory)sessionStorage.setItem('phone-history:'+id,JSON.stringify({...activeHistory,supportMode:selected}));navigate(id,selected);}
 function tab(id){for(const b of document.querySelectorAll('[data-phone-tab]')){const active=b.dataset.phoneTab===id;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;if(active){const host=b.parentElement,left=b.offsetLeft-host.offsetLeft;if(left<host.scrollLeft)host.scrollLeft=left;else if(left+b.offsetWidth>host.scrollLeft+host.clientWidth)host.scrollLeft=left+b.offsetWidth-host.clientWidth;}$(b.getAttribute('aria-controls')).hidden=!active;}const addButton=$('phoneContactAddToggle');if(addButton)addButton.hidden=id!=='contacts';if(id!=='contacts'&&$('phoneContactForm')?.open)$('phoneContactForm').close();}
 function home(id='dial'){if(state().joined){msg('通話を終了してからホームへ戻ってください。');return;}const u=new URL(location.origin+location.pathname);u.searchParams.set('tab',id);location.assign(u);}
 async function copy(t){try{await navigator.clipboard.writeText(t);msg('コピーしました。');}catch(_){msg(t);}}
 function numberLink(){const u=new URL(location.origin+location.pathname);u.searchParams.set('contact',own);return u.toString();}
 async function createNumber(){if(busy)return;const display=$('phoneName').value.trim();if(!display){$('phoneNameDialog').showModal();$('phoneNameMessage').textContent='番号を作る前に、名前を保存してください。';$('phoneName').focus();return;}busy=true;
  try{for(let i=0;i<10;i++){const n=crypto.getRandomValues(new Uint32Array(1))[0];if(n>=4200000000){i--;continue;}const number=String(n%1e8).padStart(8,'0');const value=await tx(async t=>{const p=await t.get(profile);if(p.exists())return p.data().number;const s=await t.get(ref('voiceNumbers',number));if(s.exists())return null;t.set(ref('voiceNumbers',number),{number,ownerUid:uid});t.set(profile,{number,name:display.slice(0,20)});return number;});if(value){own=value;renderOwn();msg('自分の番号を作成しました。');return;}}throw Error();}catch(_){msg('番号を作れませんでした。通信を確認してください。');}finally{busy=false;}}
 function renderOwn(){$('phoneOwnNumber').textContent=own?formatNumber(own):'番号を設定してください';$('phoneCreateNumber').hidden=!!own;$('phoneCopy').hidden=!own;$('phoneQr').hidden=!own;}
 async function saveName(){const value=Array.from($('phoneName').value.normalize('NFKC').replace(/\s+/g,' ').trim()).slice(0,8).join('');if(!value){$('phoneNameMessage').textContent='名前を入力してください。';return;}if(own)await patch(profile,{name:value});$('phoneName').value=value;$('nameInput').value=value;$('nameInput').dispatchEvent(new Event('change',{bubbles:true}));$('phoneNameOpen').title=value+'：名前を編集';$('phoneNameDialog').close();msg('名前を保存しました。');}

 function myName(){return $('nameInput').value.trim().slice(0,8)||name();}
 async function addContact(number=$('phoneContactNumber').value,alias=$('phoneContactName').value,reading=$('phoneContactReading').value){const n=normalizeNumber(number);if(!n||!alias.trim()){msg('8桁の番号と登録名を入力してください。');return;}const s=await read(ref('voiceNumbers',n));if(!s.exists()||s.data().ownerUid===uid){msg('相手の番号を確認してください。');return;}const previous=contacts.find(c=>c.number===n);await write(doc(db,'numberProfiles',uid,'contacts',n),{number:n,name:alias.trim().slice(0,40),reading:reading.trim().slice(0,40),uid:s.data().ownerUid,favorite:!!previous?.favorite});$('phoneContactNumber').value='';$('phoneContactName').value='';$('phoneContactReading').value='';if($('phoneContactForm').open)$('phoneContactForm').close();$('phoneContactAddToggle').setAttribute('aria-expanded','false');msg('電話帳に登録しました。相手側には自動登録されません。');}
 function renderContacts(){const shown=filterPhoneItems(contacts,$('phoneContactSearch').value),groups=groupContacts(shown);$('phoneContacts').innerHTML=groups.length?groups.map(group=>`<section class="contact-section"><h3>${esc(group.label)}</h3>${group.items.map(c=>`<article class="phone-row contact-row"><div><strong>${esc(c.name)}</strong><small>${esc(formatNumber(c.number))}</small></div><button data-favorite="${c.number}" aria-label="${c.favorite?'お気に入りを解除':'お気に入りに追加'}"><i class="fa-${c.favorite?'solid':'regular'} fa-star"></i></button><button data-dial="${c.number}"><i class="fa-solid fa-phone"></i> 電話</button><button data-edit="${c.number}">編集</button><button data-block-contact="${c.number}" data-uid="${esc(c.uid)}" data-name="${esc(c.name)}">ブロック</button><button data-remove-contact="${c.number}" aria-label="${esc(c.name)}を削除">削除</button></article>`).join('')}</section>`).join(''):contacts.length?'<p>一致する相手はいません。</p>':'';$('groupInviteContact').innerHTML='<option value="">電話帳から選ぶ</option>'+contacts.map(c=>`<option value="${esc(c.uid)}">${c.favorite?'★ ':''}${esc(c.name)}</option>`).join('');renderFrequent();}
 async function history(id,data){try{await write(doc(db,'numberProfiles',uid,'history',id),{...data,at:Date.now()});}catch(_){}}
 function recentMode(number){return mode(historyItems.find(item=>item.number===number)?.supportMode??defaultMode())}
 function renderFrequent(){const targets=frequentHistoryTargets(historyItems,contacts);$('phoneFrequent').innerHTML=targets.map(item=>`<article class="frequent-card"><i class="fa-solid fa-circle-user" aria-hidden="true"></i><button data-dial="${esc(item.number)}" data-dial-name="${esc(item.name)}" data-dial-mode="${recentMode(item.number)}" aria-label="${esc(item.name)}さんに電話"><i class="fa-solid fa-phone" aria-hidden="true"></i></button><strong>${esc(item.name)}</strong></article>`).join('')||'<p class="frequent-empty">履歴が増えると、よく使う相手がここに表示されます。</p>';}
 function renderHistory(){const shown=groupHistory(filterPhoneItems(historyItems,$('phoneHistorySearch').value));$('phoneHistory').innerHTML=shown.map(h=>{const displayName=preferredHistoryName(h,contacts),registered=contacts.some(c=>c.number===h.number),missed=h.status==='missed'||h.status==='declined',supportMode=mode(h.supportMode);const detail=[h.direction==='outgoing'?'発信':'着信',historyLabels[h.status]||h.status,modeLabel(supportMode),h.durationSeconds?formatDuration(h.durationSeconds):'',formatHistoryDate(h.at)].filter(Boolean).join('・'),entries=h.count>1?`<details class="history-details"><summary>${h.count}件の詳細</summary>${h.entries.map(entry=>`<div><span>${esc(historyLabels[entry.status]||entry.status)}・${esc(modeLabel(entry.supportMode))}</span><time>${esc(formatHistoryDate(entry.at))}</time></div>`).join('')}</details>`:'';return `<article class="phone-row history-row ${missed?'is-missed':''}"><i class="fa-solid fa-user" aria-hidden="true"></i><div><strong>${esc(displayName)}${h.count>1?` <span class="history-count">${h.count}件</span>`:''}</strong><small>${esc(formatNumber(h.number||''))}</small><small>${esc(detail)}</small>${entries}</div>${h.number&&!registered?`<button data-register="${esc(h.number)}" data-name="${esc(displayName)}" aria-label="電話帳に登録"><i class="fa-solid fa-address-book"></i><span>登録</span></button>`:''}${h.id?`<button data-remove-history="${esc(h.id)}" aria-label="この履歴を削除"><i class="fa-solid fa-trash-can"></i><span>削除</span></button>`:''}${h.number?`<button data-dial="${esc(h.number)}" data-dial-name="${esc(displayName)}" data-dial-mode="${supportMode}" aria-label="電話する"><i class="fa-solid fa-phone"></i><span>電話</span></button>`:''}</article>`}).join('')||'<p>'+(historyItems.length?'一致する履歴はありません。':'発着信履歴はまだありません。')+'</p>';renderFrequent();}

 function showCallResult(status,nameValue,number,supportMode=defaultMode()){const dialog=$('phoneCallResultDialog');$('phoneCallResultStatus').textContent=status;$('phoneCallResultName').textContent=nameValue||'相手';$('phoneCallResultNumber').textContent=formatNumber(number||'');dialog.dataset.number=number||'';dialog.dataset.name=nameValue||'';dialog.dataset.mode=mode(supportMode);if(!dialog.open)dialog.showModal();}
 function stopRingtone(){clearInterval(ringAudioTimer);ringAudioTimer=null;try{ringAudio?.close();}catch(_){}ringAudio=null;}
 function startRingtone(){if(!$('phoneRingtone').checked||ringAudioTimer)return;const beep=()=>{try{const Audio=window.AudioContext||window.webkitAudioContext;ringAudio??=new Audio();const osc=ringAudio.createOscillator(),gain=ringAudio.createGain();osc.frequency.value=660;gain.gain.setValueAtTime(.0001,ringAudio.currentTime);gain.gain.exponentialRampToValueAtTime(.12,ringAudio.currentTime+.03);gain.gain.exponentialRampToValueAtTime(.0001,ringAudio.currentTime+.45);osc.connect(gain).connect(ringAudio.destination);osc.start();osc.stop(ringAudio.currentTime+.5);}catch(_){}};beep();ringAudioTimer=setInterval(beep,1800);}
 async function available(t,id){const s=await t.get(busyRef(id));if(!s.exists()||!isLeaseLive(s.data(),Date.now()))return true;const b=s.data();if(b.callId.startsWith('n_')){const r=await t.get(ref('numberVoiceCalls',b.callId));return !r.exists()||!r.data().active;}return false;}
 function dial(value,savedName='',supportMode=null){const number=normalizeNumber(value);if(!number){msg('8桁の番号を入力してください。');return;}const selected=supportMode==null?defaultMode():mode(supportMode),dialog=$('phoneDialConfirm'),targetName=contacts.find(c=>c.number===number)?.name||savedName||'';$('phoneDialConfirmName').textContent=targetName||'名前未登録';$('phoneDialConfirmNumber').textContent=formatNumber(number);dialog.dataset.number=number;dialog.dataset.name=targetName;const radio=document.querySelector('input[name="phoneSupportMode"][value="'+selected+'"]');if(radio)radio.checked=true;if(!dialog.open)dialog.showModal();}
 async function dialNow(value,savedName='',supportMode='support'){if(busy||outgoing)return;if(state().joined){msg('通話を終了してから発信してください。');return;}const number=normalizeNumber(value);if(!number){msg('8桁の番号を入力してください。');return;}if(!own){msg('先に自分の番号を作成してください。');return;}supportMode=mode(supportMode);const targetName=contacts.find(c=>c.number===number)?.name||savedName||formatNumber(number);busy=true;
  try{const target=await read(ref('voiceNumbers',number));if(!target.exists()||target.data().ownerUid===uid)throw Error('相手の番号を確認してください。');const to=target.data().ownerUid;const id=uid+'_'+Date.now();
   // Even busy calls are recorded as requests so the callee gets a missed-call entry.
   await write(requestRef(uid),{from:uid,to,number,fromNumber:own,name:myName(),supportMode,status:'ringing',createdAt:serverTimestamp(),expiresAt:Timestamp.fromMillis(Date.now()+85000)});
    outgoing=true;outgoingTargetUid=to;outgoingPushId=uid+Date.now();outgoingNumber=number;outgoingName=targetName;outgoingMode=supportMode;$('phoneCancel').hidden=false;msg(targetName+'さんを'+modeLabel(supportMode)+'で呼び出しています。');await history(id,{number,name:targetName,status:'ringing',direction:'outgoing',supportMode});
   ringOff=watch(requestRef(uid),s=>{const r=s.data();if(!outgoing||!r)return;if(r.status==='accepted'){finishRing();msg(targetName+'さんが応答しました。音声を接続しています。');activeHistory={id,startedAt:Date.now(),number,name:targetName,direction:'outgoing',supportMode};history(id,{number,name:activeHistory.name,status:r.status,direction:'outgoing',startedAt:activeHistory.startedAt,supportMode}).then(()=>go(r.roomId,supportMode));}else if(r.status!=='ringing'){finishRing();history(id,{number,name:targetName,status:r.status,direction:'outgoing',supportMode});const status=r.status==='busy'?'通話中':r.status==='declined'?'応答なし':'呼び出し終了';msg(targetName+'さん：'+status);showCallResult(status,targetName,number,supportMode);}});
   ringTimer=setTimeout(()=>cancel('応答がありませんでした。'),85000);
    const targetBusy=await read(busyRef(to));if(!isLeaseLive(targetBusy.data(),Date.now()))push?.(to,{action:'ring',invitationId:outgoingPushId}).catch(()=>{});
  }catch(e){msg(e.code==='permission-denied'?'発信できません。連続発信の場合は30秒以上待ってください。':e.message||'発信できませんでした。');}finally{busy=false;}}
 function finishRing(){outgoing=false;ringOff?.();ringOff=null;clearTimeout(ringTimer);$('phoneCancel').hidden=true;}
 async function cancel(text='呼び出しを取り消しました。'){if(!outgoing)return;const target=outgoingTargetUid,pushId=outgoingPushId,number=outgoingNumber,targetName=outgoingName,supportMode=outgoingMode;finishRing();const tasks=[patch(requestRef(uid),{status:'cancelled'})];if(target&&pushId)tasks.push(Promise.resolve(push?.(target,{action:'cancel',invitationId:pushId})));await Promise.allSettled(tasks);outgoingTargetUid='';outgoingPushId='';outgoingNumber='';outgoingName='';msg(text);if(text==='応答がありませんでした。')showCallResult('応答なし',targetName,number,supportMode);}
 async function receive(items){const now=Date.now();for(const r of items){if(!r.createdAt)continue;const id=r.from+'_'+r.createdAt.toMillis();if(queue.has(id))continue;if(r.status==='ringing'&&r.expiresAt.toMillis()>now){if(state().joined||!(await available({get:read},uid))){queue.add(id);await patch(requestRef(r.from),{status:'busy'}).catch(()=>{});await history(id,{number:r.fromNumber||'',name:r.name,status:'busy',direction:'incoming',supportMode:mode(r.supportMode)});}}}
  incoming=items.filter(r=>r.createdAt&&r.status==='ringing'&&r.expiresAt.toMillis()>Date.now()&&!queue.has(r.from+'_'+r.createdAt.toMillis())).sort((a,b)=>a.createdAt.toMillis()-b.createdAt.toMillis())[0]||null;clearTimeout(incomingTimer);
   if(!incoming){stopRingtone();$('numberIncoming').close();return;}const id=incoming.from+'_'+incoming.createdAt.toMillis(),supportMode=mode(incoming.supportMode);history(id,{number:incoming.fromNumber||'',name:incoming.name,status:'ringing',direction:'incoming',supportMode});$('numberCaller').textContent=(contacts.find(c=>c.number===incoming.fromNumber)?.name||incoming.name||'名前未登録');$('numberCallerNumber').textContent=formatNumber(incoming.fromNumber||'');$('numberIncomingText').textContent='1対1・'+modeLabel(supportMode);try{navigator.vibrate?.([180,120,180]);}catch(_){}if(!$('numberIncoming').open)$('numberIncoming').showModal();startRingtone();incomingTimer=setTimeout(()=>{history(id,{number:incoming.fromNumber||'',name:incoming.name,status:'missed',direction:'incoming',supportMode});receive(items);},Math.max(1,incoming.expiresAt.toMillis()-Date.now()+50));}
 async function handlePushState(data){if(!data||data.type!=='kouryu-phone-state'||!data.callerUid)return;const caller=String(data.callerUid);if(data.action==='cancel'){if(incoming?.from===caller)await receive([]);return;}try{const snapshot=await read(requestRef(caller)),item=snapshot.data();if(item?.to===uid&&item.status==='ringing')await receive([item]);}catch(_){} }
 async function respond(accept){if(busy||!incoming)return;stopRingtone();busy=true;const r=incoming,id=r.from+'_'+r.createdAt.toMillis();$('numberAccept').disabled=true;
  try{const supportMode=mode(r.supportMode);if(!accept){await patch(requestRef(r.from),{status:'declined'});await history(id,{number:r.fromNumber||'',name:r.name,status:'declined',direction:'incoming',supportMode});return;}if(state().joined)throw Error('現在の通話を終了してから応答してください。');const callId='n_'+crypto.randomUUID().replaceAll('-','');
   await tx(async t=>{const pending=await t.get(requestRef(r.from));if(pending.data()?.status!=='ringing'||pending.data().expiresAt.toMillis()<=Date.now())throw Error('この着信は終了しました。');const selfFree=await available(t,uid),otherFree=await available(t,r.from);if(!selfFree||!otherFree)throw Error('どちらかが通話中です。');t.set(ref('numberVoiceCalls',callId),{ownerUid:uid,number:own,members:[uid,r.from],supportMode,active:true,expiresAt:Timestamp.fromMillis(Date.now()+65*60000)});t.update(requestRef(r.from),{status:'accepted',roomId:callId});for(const person of [uid,r.from])t.set(busyRef(person),{callId,until:Timestamp.fromMillis(Date.now()+240000)});});
   queue.add(id);$('numberIncoming').close();activeHistory={id,startedAt:Date.now(),number:r.fromNumber||'',name:r.name,direction:'incoming',supportMode};await history(id,{number:activeHistory.number,name:r.name,status:'accepted',direction:'incoming',startedAt:activeHistory.startedAt,supportMode});go(callId,supportMode);
  }catch(e){$('numberIncomingText').textContent=e.message||'応答できませんでした。';}finally{busy=false;$('numberAccept').disabled=false;}}
 async function block(){const r=incoming;if(!r)return;stopRingtone();await write(doc(db,'voiceNumbers',own,'blocked',r.from),{name:r.name,number:r.fromNumber||''});await respond(false);}
 let qrStream=null,qrTimer=null;
 function closeQrScan(){clearInterval(qrTimer);qrTimer=null;qrStream?.getTracks().forEach(t=>t.stop());qrStream=null;if($('phoneQrScanDialog').open)$('phoneQrScanDialog').close();}
 function useQrValue(raw){let value=String(raw||'');try{value=new URL(value,location.href).searchParams.get('contact')||value;}catch(_){}const number=normalizeNumber(value);if(!number)return false;closeQrScan();tab('contacts');$('phoneContactNumber').value=number;$('phoneContactName').focus();msg('番号を読み取りました。登録する名前を入力してください。');return true;}
 async function scanQr(){if(!navigator.mediaDevices?.getUserMedia){msg('このブラウザではカメラを利用できません。相手の番号を入力してください。');return;}try{const detector='BarcodeDetector' in window?new BarcodeDetector({formats:['qr_code']}):null;if(!detector&&typeof window.jsQR!=='function')throw Error('QR読み取り機能を読み込めませんでした。');qrStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});const video=$('phoneQrVideo'),canvas=$('phoneQrCanvas');video.srcObject=qrStream;await video.play();$('phoneQrScanDialog').showModal();$('phoneQrScanStatus').textContent='カメラをQRコードへ向けてください。';qrTimer=setInterval(async()=>{try{if(detector){const codes=await detector.detect(video);if(codes.length)useQrValue(codes[0].rawValue);return;}if(!video.videoWidth||!video.videoHeight)return;canvas.width=video.videoWidth;canvas.height=video.videoHeight;const context=canvas.getContext('2d',{willReadFrequently:true});context.drawImage(video,0,0,canvas.width,canvas.height);const image=context.getImageData(0,0,canvas.width,canvas.height),code=window.jsQR(image.data,image.width,image.height,{inversionAttempts:'dontInvert'});if(code)useQrValue(code.data);}catch(_){}},300);}catch(e){closeQrScan();msg(e.name==='NotAllowedError'?'カメラの使用が許可されていません。ブラウザの設定を確認してください。':e.message||'カメラを開始できませんでした。');}}
 function groupLink(g){const u=new URL(location.origin+location.pathname);u.searchParams.set('groupInvite',g.id);return u.toString();}
 async function createGroup(){const title=$('phoneGroupName').value.trim().slice(0,40);if(!title){msg('グループ名を入力してください。');return;}const id='g_'+crypto.randomUUID().replaceAll('-','');await write(ref('phoneGroups',id),{name:title,ownerUid:uid,members:[uid],memberNames:{[uid]:myName()},supportMode:defaultMode(),active:true});$('phoneGroupName').value='';await openGroup(id);msg('グループを作成しました。電話帳かリンクから招待してください。');}
 function renderInvites(){$('phoneGroupInvites').innerHTML=groupInvites.filter(d=>!groups.some(g=>g.id===d.groupId)).map(d=>`<article class="phone-row"><span>${esc(d.name)}への招待</span><button data-open-group="${esc(d.groupId)}">招待を確認</button></article>`).join('');}
 function renderGroups(){renderInvites();$('phoneGroups').innerHTML=groups.map(g=>`<article class="phone-row"><div><strong>${esc(g.name)}</strong><small>${g.members.length}/4人</small></div><button data-open-group="${esc(g.id)}">開く</button></article>`).join('');}
 async function openGroup(id){const s=await read(ref('phoneGroups',id));if(!s.exists()||!s.data().active){msg('このグループは終了しています。');return;}selectedGroup={...s.data(),supportMode:mode(s.data().supportMode),id};const g=selectedGroup;$('groupTitle').textContent=g.name;$('groupMembers').textContent=g.members.length+'/4人のグループ';$('groupAcceptInvite').hidden=g.members.includes(uid);$('groupDeclineInvite').hidden=g.members.includes(uid);$('groupJoin').hidden=!g.members.includes(uid);$('groupShare').hidden=!g.members.includes(uid);$('groupInviteArea').hidden=!g.members.includes(uid);$('groupDelete').hidden=g.ownerUid!==uid;$('groupOwnerTools').hidden=g.ownerUid!==uid;$('groupRename').value=g.name;for(const radio of document.querySelectorAll('input[name="groupSupportMode"]')){radio.checked=radio.value===g.supportMode;radio.disabled=g.ownerUid!==uid;}renderGroupMembers();$('groupQuit').hidden=g.ownerUid===uid||!g.members.includes(uid);$('groupDialog').showModal();groupDetailOff?.();groupDetailOff=watch(ref('phoneGroups',id),snap=>{if(!snap.data()?.active){$('groupDialog').close();return;}selectedGroup={...snap.data(),supportMode:mode(snap.data().supportMode),id};for(const radio of document.querySelectorAll('input[name="groupSupportMode"]'))radio.checked=radio.value===selectedGroup.supportMode;$('groupMembers').textContent=selectedGroup.members.length+'/4人のグループ';renderGroupMembers();});groupPeopleOff?.();$('groupPeople').textContent='参加するとマイクを使います。';if(g.members.includes(uid))groupPeopleOff=watch(query(collection(db,'groupVoiceCalls',id,'participants'),where('left','==',false)),s=>{const active=s.docs.map(d=>d.data()).filter(d=>Date.now()-(d.lastSeenAt?.toMillis()||0)<240000);$('groupPeople').textContent=active.length?'通話中：'+active.map(d=>d.userName).join('、'):'いま通話中の人はいません。';});}
 function renderGroupMembers(){const g=selectedGroup;if(!g)return;$('groupMemberList').innerHTML=g.members.map(member=>`<div><span>${esc(g.memberNames?.[member]||(member===uid?myName():'メンバー'))}${member===g.ownerUid?'（管理者）':''}</span>${g.ownerUid===uid&&member!==uid?`<button data-remove-member="${esc(member)}">退出させる</button>`:''}</div>`).join('');}
 async function acceptGroup(){const id=selectedGroup?.id;if(!id)return;await tx(async t=>{const s=await t.get(ref('phoneGroups',id)),g=s.data();if(!canJoinGroup(g,uid))throw Error('グループが満員、または終了しています。');if(!g.members.includes(uid))t.update(ref('phoneGroups',id),{members:[...g.members,uid],memberNames:{...(g.memberNames||{}),[uid]:myName()}});});await patch(ref('phoneGroupInvites',id+'_'+uid),{status:'accepted'}).catch(()=>{});await openGroup(id);msg('グループに登録しました。通話するには「通話に参加」を押してください。');}
 async function declineGroup(){const g=selectedGroup;if(!g)return;await patch(ref('phoneGroupInvites',g.id+'_'+uid),{status:'declined'});$('groupDialog').close();msg('招待を辞退しました。');}
 async function renameGroup(){const value=$('groupRename').value.trim().slice(0,40);if(!value)return;await patch(ref('phoneGroups',selectedGroup.id),{name:value});$('groupTitle').textContent=value;msg('グループ名を変更しました。');}
 async function removeMember(member){const g=selectedGroup;if(!g||g.ownerUid!==uid)return;const memberNames={...(g.memberNames||{})};delete memberNames[member];await patch(ref('phoneGroups',g.id),{members:g.members.filter(x=>x!==member),memberNames});}
 async function saveGroupMode(){const g=selectedGroup;if(!g||g.ownerUid!==uid)return;const previous=mode(g.supportMode), supportMode=selectedMode('groupSupportMode');if(supportMode===previous)return;const snap=await getDocs(query(collection(db,'groupVoiceCalls',g.id,'participants'),where('left','==',false)));const now=Date.now(), active=snap.docs.some(d=>{const data=d.data(),seen=data.lastSeenAt?.toMillis?.()||data.joinedAt?.toMillis?.()||Number(data.lastSeenAt||data.lastSeen||data.joinedAt||0);return seen>now-240000;});if(active){for(const radio of document.querySelectorAll('input[name="groupSupportMode"]'))radio.checked=radio.value===previous;msg('通話中は種類を変更できません。');return;}await patch(ref('phoneGroups',g.id),{supportMode});selectedGroup.supportMode=supportMode;msg('通話の種類を'+modeLabel(supportMode)+'にしました。');}
 async function joinGroup(){if(state().joined){msg('今の通話を終了してから参加してください。');return;}const id=selectedGroup?.id;if(!id)return;await tx(async t=>{const s=await t.get(ref('phoneGroups',id));if(!s.data()?.active||!s.data().members.includes(uid))throw Error('グループへの登録が必要です。');if(!(await available(t,uid)))throw Error('別の端末で通話中です。');t.set(busyRef(uid),{callId:id,until:Timestamp.fromMillis(Date.now()+240000)});});go(id,selectedGroup.supportMode);}
 async function inviteContact(){const to=$('groupInviteContact').value,g=selectedGroup;if(!to||!g)return;if(g.members.length>=4){msg('グループは4人までです。');return;}await write(ref('phoneGroupInvites',g.id+'_'+to),{groupId:g.id,to,from:uid,name:g.name,status:'invited'});msg('グループへの招待を送りました。');}
 async function quitGroup(deleting){const g=selectedGroup;if(!g)return;if(!(await askConfirmation(deleting?'全員がこのグループを利用できなくなります。':'再参加するには、もう一度招待してもらう必要があります。',{title:deleting?'グループを削除しますか？':'グループから退出しますか？',confirmLabel:deleting?'削除する':'退出する',danger:true})))return;if(deleting)await patch(ref('phoneGroups',g.id),{active:false});else await tx(async t=>{const s=await t.get(ref('phoneGroups',g.id));t.update(ref('phoneGroups',g.id),{members:s.data().members.filter(x=>x!==uid),memberNames:Object.fromEntries(Object.entries(s.data().memberNames||{}).filter(([k])=>k!==uid))});});$('groupDialog').close();}
 async function account(mode){if(state().joined||outgoing){msg('通話・呼び出しを終了してから操作してください。');return;}const email=$('phoneEmail').value.trim(),password=$('phonePassword').value;try{if(mode==='save'){await linkWithCredential(user,EmailAuthProvider.credential(email,password));$('accountStatus').textContent='番号を引き継げるようにしました。';try{await sendEmailVerification(user);$('accountStatus').textContent+='確認メールをご確認ください。';}catch(_){$('accountStatus').textContent+='確認メールの送信は再度お試しください。';}$('phonePassword').value='';}else if(mode==='login'){if(own&&user.isAnonymous&&!(await askConfirmation('現在の番号は自動で統合されません。登録済みの番号と電話帳へ切り替えます。',{title:'登録済みアカウントへ切り替えますか？',confirmLabel:'切り替える'})))return;await signInWithEmailAndPassword(auth,email,password);location.assign(location.origin+location.pathname);}else if(mode==='reset'){await sendPasswordResetEmail(auth,email);$('accountStatus').textContent='登録済みのメールアドレスの場合、再設定メールが届きます。';}else{if(user.isAnonymous){$('accountStatus').textContent='先に「この番号を保存」を設定してください。';return;}await signOut(auth);location.assign(location.origin+location.pathname);}}catch(e){$('accountStatus').textContent=e.code==='auth/email-already-in-use'?'このメールは登録済みです。「ログイン」をお試しください。':e.code==='auth/weak-password'?'パスワードは6文字以上にしてください。':'操作できませんでした。メール・パスワード・通信状態を確認してください。';}}
 async function allowed(){const id=state().callId;try{if(id.startsWith('n_')){const s=await read(ref('numberVoiceCalls',id));currentRoom=s.data();return !!currentRoom?.active&&currentRoom.members.length===2&&currentRoom.members.includes(uid)&&currentRoom.expiresAt.toMillis()>Date.now()&&mode(currentRoom.supportMode)===mode(state().supportMode);}if(id.startsWith('g_')){const s=await read(ref('phoneGroups',id)),g=s.data();return !!g?.active&&g.members.includes(uid)&&mode(g.supportMode)===mode(state().supportMode);}return false;}catch(_){return false;}}
 async function acquire(){if(!(await allowed()))return false;const id=state().callId;await tx(async t=>{const b=await t.get(busyRef(uid));if(isLeaseLive(b.data(),Date.now())&&b.data().callId!==id)throw Error('別の通話に参加中です。');t.set(busyRef(uid),{callId:id,until:Timestamp.fromMillis(Date.now()+240000)});});return true;}
 async function pulse(){if(!state().joined)return;try{await patch(busyRef(uid),{until:Timestamp.fromMillis(Date.now()+240000)});}catch(_){stop();msg('通話の状態を確認できないため終了しました。');}}
 async function leave(){const id=state().callId;try{const meta=JSON.parse(sessionStorage.getItem('phone-history:'+id)||'null');if(meta){await history(meta.id,{number:meta.number||'',name:meta.name||'相手',status:'accepted',direction:meta.direction,supportMode:mode(meta.supportMode),startedAt:meta.startedAt,endedAt:Date.now(),durationSeconds:Math.max(0,Math.round((Date.now()-meta.startedAt)/1000))});sessionStorage.removeItem('phone-history:'+id);}await tx(async t=>{const b=await t.get(busyRef(uid));let room;if(id.startsWith('n_'))room=await t.get(ref('numberVoiceCalls',id));if(room?.data()?.active)t.update(ref('numberVoiceCalls',id),{active:false});if(b.data()?.callId===id)t.delete(busyRef(uid));});}catch(_){}document.body.classList.add('phone-home');}
 async function start(){
  document.body.classList.toggle('phone-home',!/^n_|^g_/.test(state().callId));
  document.querySelector('.participant-limit').textContent=state().callId.startsWith('n_')?'1対1':'最大4人';$('phoneToGroup').hidden=!state().callId.startsWith('n_');
  $('phoneName').value=name()==='匿名さん'?'':name();$('accountStatus').textContent=user.isAnonymous?'番号・電話帳・グループを別の端末へ引き継ぐには、メールとパスワードを登録してください。':user.email+'でログイン中';
  for(const b of document.querySelectorAll('[data-phone-tab]'))b.onclick=()=>tab(b.dataset.phoneTab);
  $('shareBtn').textContent=state().callId.startsWith('g_')?'招待リンク':'番号を共有';$('shareBtn').addEventListener('click',e=>{e.stopImmediatePropagation();copy(state().callId.startsWith('g_')?groupLink({id:state().callId}):numberLink());},true);
  const bind=(id,fn)=>$(id).addEventListener('click',async()=>{const b=$(id);b.disabled=true;try{await fn();}catch(e){msg(e.message||'操作できませんでした。');}finally{b.disabled=false;}});
  bind('phoneQr',()=>{if(!own){msg('先に自分の番号を作成してください。');return;}const qr=qrcode(0,'M');qr.addData(numberLink());qr.make();$('phoneQrImage').innerHTML=qr.createSvgTag({cellSize:5,margin:3,scalable:true});$('phoneQrNumber').textContent=formatNumber(own);$('phoneQrDialog').showModal();});bind('phoneQrClose',()=>$('phoneQrDialog').close());bind('phoneCreateNumber',createNumber);bind('phoneCopy',()=>copyNumberFeedback($('phoneCopy'),own));bind('phoneCancel',()=>cancel());bind('phoneAddContact',()=>addContact());bind('phoneCreateGroup',createGroup);
  $('phoneContactSearch').addEventListener('input',renderContacts);$('phoneHistorySearch').addEventListener('input',renderHistory);
  bind('phoneQrScan',scanQr);bind('phoneQrScanClose',closeQrScan);$('phoneQrScanDialog').addEventListener('cancel',e=>{e.preventDefault();closeQrScan();});
  const closeDialConfirm=()=>{$('phoneDialConfirm').close();};bind('phoneDialConfirmClose',closeDialConfirm);bind('phoneDialConfirmCancel',closeDialConfirm);bind('phoneDialConfirmCall',async()=>{const dialog=$('phoneDialConfirm'),number=dialog.dataset.number,savedName=dialog.dataset.name,supportMode=selectedMode('phoneSupportMode');localStorage.setItem(defaultModeKey,supportMode);for(const radio of document.querySelectorAll('input[name="phoneDefaultMode"]'))radio.checked=radio.value===supportMode;closeDialConfirm();await dialNow(number,savedName,supportMode);});
  for(const radio of document.querySelectorAll('input[name="groupSupportMode"]'))radio.addEventListener('change',()=>saveGroupMode().catch(e=>msg(e.message||'変更できませんでした。')));
  const closeContactForm=()=>{const dialog=$('phoneContactForm');if(dialog.open)dialog.close();$('phoneContactAddToggle').setAttribute('aria-expanded','false');};
  const openContactForm=()=>{const dialog=$('phoneContactForm');$('phoneContactAddToggle').setAttribute('aria-expanded','true');if(!dialog.open)dialog.showModal();window.setTimeout(()=>$('phoneContactNumber').focus(),0);};
  bind('phoneContactFormClose',closeContactForm);$('phoneContactForm').addEventListener('cancel',e=>{e.preventDefault();closeContactForm();});$('phoneContactForm').addEventListener('click',e=>{if(e.target===$('phoneContactForm'))closeContactForm();});
  const closeCallResult=()=>{$('phoneCallResultDialog').close();};bind('phoneCallResultClose',closeCallResult);bind('phoneCallResultHistory',()=>{closeCallResult();tab('history');});bind('phoneCallResultRegister',()=>{const dialog=$('phoneCallResultDialog');closeCallResult();tab('contacts');openContactForm();$('phoneContactNumber').value=dialog.dataset.number;$('phoneContactName').value=dialog.dataset.name;});bind('phoneCallResultRedial',()=>{const dialog=$('phoneCallResultDialog'),number=dialog.dataset.number,savedName=dialog.dataset.name,supportMode=dialog.dataset.mode;closeCallResult();dial(number,savedName,supportMode);});
  $('phoneConfirmClose').onclick=()=>closeConfirmation(false);$('phoneConfirmCancel').onclick=()=>closeConfirmation(false);$('phoneConfirmOk').onclick=()=>closeConfirmation(true);$('phoneConfirmDialog').addEventListener('cancel',e=>{e.preventDefault();closeConfirmation(false);});$('phoneConfirmDialog').addEventListener('click',e=>{if(e.target===$('phoneConfirmDialog'))closeConfirmation(false);});
  for(const [id,close] of [['phoneDialConfirm',closeDialConfirm],['phoneCallResultDialog',closeCallResult],['phoneQrScanDialog',closeQrScan]])$(id).addEventListener('click',e=>{if(e.target===$(id))close();});
  bind('phoneHistoryClear',async()=>{if(!historyItems.length||!(await askConfirmation('保存されている発着信履歴をすべて削除します。',{title:'すべての履歴を削除しますか？',confirmLabel:'すべて削除',danger:true})))return;const snap=await getDocs(collection(db,'numberProfiles',uid,'history'));await Promise.all(snap.docs.map(item=>remove(item.ref)));msg('発着信履歴をすべて削除しました。');});
  const ringKey='kouryu-phone-ringtone-v1';for(const radio of document.querySelectorAll('input[name="phoneDefaultMode"]')){radio.checked=radio.value===defaultMode();radio.addEventListener('change',()=>{if(!radio.checked)return;localStorage.setItem(defaultModeKey,mode(radio.value));msg('いつも使う通話を「'+modeLabel(radio.value)+'」にしました。');});}$('phoneRingtone').checked=localStorage.getItem(ringKey)!=='off';$('phoneRingtone').addEventListener('change',()=>{localStorage.setItem(ringKey,$('phoneRingtone').checked?'on':'off');if(!$('phoneRingtone').checked)stopRingtone();});
  const refreshNotificationStatus=()=>{$('phoneNotificationStatus').textContent=notifications.status?.()||'このブラウザでは通知状態を確認できません。';};refreshNotificationStatus();bind('phoneNotificationEnable',async()=>{await notifications.enable?.();refreshNotificationStatus();});bind('phoneNotificationTest',async()=>{await notifications.test?.();refreshNotificationStatus();msg('テスト通知を表示しました。');});
  $('phoneNameOpen').onclick=()=>{$('phoneNameMessage').textContent='';$('phoneNameDialog').showModal();$('phoneName').focus();};
  $('phoneNameClose').onclick=()=>{$('phoneName').value=$('nameInput').value;$('phoneNameDialog').close();};
  $('phoneNameDialog').addEventListener('click',e=>{if(e.target!==$('phoneNameDialog'))return;const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('phoneNameClose').click();});
  const setOwnOpen=open=>{$('phoneOwnToggle').setAttribute('aria-expanded',String(open));$('phoneOwnDetails').classList.toggle('is-visible',open);$('phoneOwnDetails').inert=!open;$('phoneOwnDetails').setAttribute('aria-hidden',String(!open));};
  $('phoneOwnToggle').onclick=()=>setOwnOpen($('phoneOwnToggle').getAttribute('aria-expanded')!=='true');
  const setCollapsible=(buttonId,panelId,open)=>{const button=$(buttonId),panel=$(panelId);button.setAttribute('aria-expanded',String(open));panel.classList.toggle('is-visible',open);panel.inert=!open;panel.setAttribute('aria-hidden',String(!open));};
  $('accountHelpToggle').onclick=()=>setCollapsible('accountHelpToggle','accountHelpPanel',$('accountHelpToggle').getAttribute('aria-expanded')!=='true');
  $('defaultModeHelpToggle').onclick=()=>setCollapsible('defaultModeHelpToggle','defaultModeHelpPanel',$('defaultModeHelpToggle').getAttribute('aria-expanded')!=='true');
  for(const input of [$('phoneEmail'),$('phonePassword')])input.addEventListener('input',syncAccountActions);syncAccountActions();
  $('phoneHistoryToolsToggle').onclick=()=>setCollapsible('phoneHistoryToolsToggle','phoneHistoryTools',$('phoneHistoryToolsToggle').getAttribute('aria-expanded')!=='true');
  $('phoneContactAddToggle').onclick=openContactForm;
  $('phoneDialPanel').addEventListener('keydown',e=>{if(e.key==='Escape'){setOwnOpen(false);$('phoneOwnToggle').focus();}});
  $('phoneNameDialog').addEventListener('cancel',()=>{$('phoneName').value=$('nameInput').value;});
  $('phoneNameForm').addEventListener('submit',async e=>{e.preventDefault();$('phoneSaveName').disabled=true;try{await saveName();}catch(_){$('phoneNameMessage').textContent='保存できませんでした。通信を確認してください。';}finally{$('phoneSaveName').disabled=false;}});
  const tabs=document.querySelector('.phone-tabs');tabs.addEventListener('wheel',e=>{if(e.ctrlKey||tabs.scrollWidth<=tabs.clientWidth)return;const before=tabs.scrollLeft;tabs.scrollLeft+=Math.abs(e.deltaX)>Math.abs(e.deltaY)?e.deltaX:e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?tabs.clientWidth:1);if(before!==tabs.scrollLeft)e.preventDefault();},{passive:false});
  tabs.addEventListener('keydown',e=>{const buttons=[...tabs.querySelectorAll('[data-phone-tab]')],i=buttons.indexOf(document.activeElement);if(i<0||!['ArrowRight','ArrowLeft','Home','End'].includes(e.key))return;e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?buttons.length-1:(i+(e.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;tab(buttons[next].dataset.phoneTab);buttons[next].focus();});
  const editDial=bindDialInput($('phoneDialNumber'));
  for(const b of document.querySelectorAll('[data-phone-key]'))b.onclick=()=>editDial(b.dataset.phoneKey);
  $('phoneBackspace').onclick=()=>editDial(null);
  $('phoneDialForm').addEventListener('submit',e=>{e.preventDefault();dial($('phoneDialNumber').value);});
  bind('numberAccept',()=>respond(true));bind('numberDecline',()=>respond(false));bind('numberBlock',block);$('numberIncoming').addEventListener('cancel',e=>{e.preventDefault();respond(false);});
  bind('groupClose',()=>{$('groupDialog').close();groupPeopleOff?.();groupDetailOff?.();});bind('groupAcceptInvite',acceptGroup);bind('groupDeclineInvite',declineGroup);bind('groupRenameSave',renameGroup);bind('groupJoin',joinGroup);bind('groupShare',()=>copy(groupLink(selectedGroup)));bind('groupInviteSend',inviteContact);bind('groupDelete',()=>quitGroup(true));bind('groupQuit',()=>quitGroup(false));
  for(const mode of ['save','login','reset','logout'])bind('account-'+mode,()=>account(mode));
  bind('phoneHomeBtn',()=>home());bind('phoneToGroup',async()=>{if(!(await askConfirmation('今の電話を終了してグループ画面へ移動します。相手にはグループ作成後に招待を送ってください。',{title:'グループ画面へ移動しますか？',confirmLabel:'移動する'})))return;await leave();stop();home('groups');});
  $('phoneHome').addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.legacyName){openContactForm();$('phoneContactName').value=d.legacyName;$('phoneContactNumber').value='';$('phoneContactNumber').focus();}if(d.dial)dial(d.dial,d.dialName,d.dialMode||null);if(d.register){tab('contacts');openContactForm();$('phoneContactNumber').value=d.register;$('phoneContactName').value=d.name||'';}if(d.edit){const c=contacts.find(c=>c.number===d.edit);openContactForm();$('phoneContactNumber').value=c.number;$('phoneContactName').value=c.name;$('phoneContactReading').value=c.reading||'';}if(d.favorite){const c=contacts.find(c=>c.number===d.favorite);patch(doc(db,'numberProfiles',uid,'contacts',d.favorite),{favorite:!c?.favorite});}if(d.removeContact&&(await askConfirmation('この端末の電話帳から削除します。',{title:'電話帳から削除しますか？',confirmLabel:'削除する',danger:true})))remove(doc(db,'numberProfiles',uid,'contacts',d.removeContact));if(d.removeHistory&&(await askConfirmation('選んだ発着信履歴を削除します。',{title:'この履歴を削除しますか？',confirmLabel:'削除する',danger:true})))remove(doc(db,'numberProfiles',uid,'history',d.removeHistory));if(d.openGroup)openGroup(d.openGroup);if(d.blockContact)write(doc(db,'voiceNumbers',own,'blocked',d.uid),{name:d.name,number:d.blockContact}).then(()=>msg('ブロックしました。'));if(d.removeMember&&(await askConfirmation('選んだメンバーをこのグループから退出させます。',{title:'メンバーを退出させますか？',confirmLabel:'退出させる',danger:true})))removeMember(d.removeMember);if(d.unblock)remove(doc(db,'voiceNumbers',own,'blocked',d.unblock));});
  const p=await read(profile);own=p.data()?.number||'';$('accountSafety').innerHTML=user.isAnonymous?'<strong>この番号はこの端末だけに保存されています。</strong><br>端末変更やデータ削除に備え、メールとパスワードで保存してください。':'<strong>番号の引き継ぎ設定済み</strong><br>別の端末でも同じアカウントで利用できます。';if(p.data()?.name){$('phoneName').value=p.data().name;$('nameInput').value=p.data().name;}renderOwn();
  watch(query(collection(db,'voiceConnections'),where('members','array-contains',uid)),s=>{const previous=s.docs.map(d=>d.data()).filter(d=>d.active!==false);$('legacyPhonebook').hidden=!previous.length;$('legacyPhoneContacts').innerHTML=previous.map(d=>{const n=d.uidA===uid?d.nameB:d.nameA;return '<article class="phone-row"><span>'+esc(n||'相手')+'</span><button data-legacy-name="'+esc(n||'相手')+'">番号を登録</button></article>';}).join('');});
  watch(collection(db,'numberProfiles',uid,'contacts'),s=>{contacts=s.docs.map(d=>d.data()).sort((a,b)=>(Number(!!b.favorite)-Number(!!a.favorite))||String(a.name).localeCompare(String(b.name),'ja'));renderContacts();});
  watch(query(collection(db,'numberProfiles',uid,'history'),orderBy('at','desc'),limit(20)),s=>{historyItems=s.docs.map(d=>({...d.data(),id:d.id}));renderHistory();});
  watch(query(collection(db,'phoneGroups'),where('members','array-contains',uid)),s=>{groups=s.docs.map(d=>({...d.data(),id:d.id})).filter(g=>g.active);renderGroups();});
  watch(query(collection(db,'phoneGroupInvites'),where('to','==',uid)),s=>{groupInvites=s.docs.map(d=>d.data()).filter(d=>d.status==='invited');renderInvites();});
  watch(query(collection(db,'numberInvitations'),where('to','==',uid),where('status','==','ringing')),s=>receive(s.docs.map(d=>d.data())).catch(()=>{}));
  if(own)watch(collection(db,'voiceNumbers',own,'blocked'),s=>{$('phoneBlocks').innerHTML=s.docs.map(d=>`<div class="phone-row"><span>${esc(d.data().name||d.data().number||'相手')}</span><button data-unblock="${esc(d.id)}">解除</button></div>`).join('')||'ブロックした相手はいません。';});
  if(/^n_|^g_/.test(state().callId))roomOff=watch(ref(state().callId.startsWith('n_')?'numberVoiceCalls':'phoneGroups',state().callId),s=>{currentRoom=s.data();if(state().joined&&(!currentRoom?.active||!currentRoom.members.includes(uid))){stop();leave();msg('通話が終了しました。');}});
  window.addEventListener('offline',()=>msg('オフラインです。通信が戻ると自動で再接続します。'));window.addEventListener('online',()=>msg('通信が戻りました。接続を確認しています。'));window.addEventListener('pagehide',()=>{closeQrScan();stopRingtone();if(outgoing)cancel();});tab(['history','contacts','dial','groups','settings'].includes(params.get('tab'))?params.get('tab'):'dial');
  if(normalizeNumber(params.get('contact')||'')){tab('contacts');$('phoneContactNumber').value=normalizeNumber(params.get('contact'));msg('登録する名前を入力して「登録」を押してください。');}
  if(params.get('groupInvite')?.match(/^g_[a-f0-9]{32}$/)){tab('groups');await openGroup(params.get('groupInvite'));}
 }
 return {start,allowed,acquire,pulse,leave,handlePushState,takeSetupUsage(){const u=usage;usage={reads:0,writes:0};return u;}};
}
